version: '3.3'
services:

  frontend:
    container_name: foodgram-frontend
    build: ../frontend
    env_file: .env
    command: cp -r /app/build/. /static/
    volumes:
      - ../static/:/static/

  backend:
    container_name: foodgram-backend
    build: ../backend
    env_file: .env
    volumes:
      - ../static/static/:/app/collected_static/
      - ../media:/app/media/
  
  proxy:
    container_name: foodgram-proxy
    build: .
    env_file: .env
    ports:
      - "80:80"
    volumes:
      - ../static/:/usr/share/nginx/html/
      - ../media:/media/
