version: '3'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
  backend:
    depends_on:
      - db
    image: pavrus/foodgram-backend
    env_file: .env
    volumes:
      - static:/static
      - media:/media
  frontend:
    image: pavrus/foodgram-frontend
    env_file: .env
    command: cp -r /app/build/. /static/
    volumes:
      - static:/static
  proxy:
    depends_on:
      - backend
      - frontend
    image: pavrus/foodgram-proxy
    env_file: .env
    ports:
      - 8080:80
    volumes:
      - static:/static
      - media:/media
